apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: postgres
spec:
  capacity:
    storage: "8Gi"
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: "/mnt/data/postgres"
---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: redis 
spec:
  capacity:
    storage: "8Gi"
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: "/mnt/data/redis"
---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: prome 
spec:
  capacity:
    storage: "10Gi"
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: "/mnt/data/prome"
---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: minio
spec:
  capacity:
    storage: "10Gi"
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: "/mnt/data/minio"
---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: gitaly 
spec:
  capacity:
    storage: "10Gi"
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: "/mnt/data/gitaly"
